###
# Build to Jar File
###
FROM maven:3.6.0-jdk-11-slim AS base

ENV HOME=/home/app
WORKDIR $HOME

COPY . .

RUN --mount=type=cache,target=/root/.m2 mvn -f $HOME/pom.xml clean package

###
# Run Application
###
FROM adoptopenjdk/openjdk11-openj9:alpine AS build-stage

COPY --from=base /home/app/booking-service/target/*.jar /app/booking-service-application.jar
COPY --from=base /home/app/booking-service/src/main/resources/ /usr/app/config/

CMD java -jar /app/booking-service-application.jar

