package mm.com.mytelpay.family.enums;

public enum ActionType {

    PRE_REGISTER_FAMILY,
    ADD_ACCOUNT,
    UPDATE_ACCOUNT,
    APPROVE_ACCOUNT,
    FORGOT_PASS,
    CHANGE_PASSWORD,
    APPROVE,
    REJECT,
    CREATE_BOOKING_CAR,
    CANCEL_BOOKING_CAR,
    REJECT_BOOKING_CAR,

    APPROVED_BOOKING_CAR,

    CREATE_BOOKING_HOTEL,

    CANCEL_BOOKING_HOTEL,

    REJECT_BOOKING_HOTEL,

    APPROVED_BOOKING_HOTEL,

    CREATE_CAR,
    EDIT_CAR,
    DELETE_CAR,

    CREATE_HOTEL,
    EDIT_HOTEL,
    DELETE_HOTEL,


    CREATE_FOOD,
    EDIT_FOOD,
    DELETE_FOOD,

    CREATE_MEAL,
    EDIT_MEAL,
    DELETE_MEAL,
    CANCEL_BOOKING_MEAL,
    CREATE_MENU,
    EDIT_MENU,
    DELETE_MENU,

    CREATE_UNIT,
    EDIT_UNIT,
    DELETE_UNIT,

    CREATE_CANTEEN,
    EDIT_CANTEEN,
    DELETE_CANTEEN,

    CREATE_FUNCTION,
    EDIT_FUNCTION,
    DELETE_FUNCTION,

    EDIT_PROFILE,
    FORGOT_PASSWORD,

    DELETE_USER,

    CREATE_TEMPLATE,
    EDIT_TEMPLATE,
    DELETE_TEMPLATE,
    UPDATE_BALANCE,

    VERIFY_QR,

    CREATE_PROVINCE,

    UPDATE_PROVINCE,

    DELETE_PROVINCE,

    CREATE_DISTRICT,
    UPDATE_DISTRICT,
    DELETE_DISTRICT,
    IMPORT_DISTRICT,
    IMPORT_CAR,
    IMPORT_PROVINCE, COMPLETE_BOOKING_CAR

}
